name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip Lambda function
        run: zip -r blackjack_game.zip .

      - name: Debug AWS CLI
        run: |
          echo "AWS CLI Version:"
          aws --version
          echo "Caller Identity:"
          aws sts get-caller-identity
          echo "Listing S3 Buckets:"
          aws s3 ls
          echo "Creating S3 Bucket:"
          aws s3 mb s3://blackjack-game-site || true
          echo "Uploading to S3:"
          aws s3 cp blackjack_game.zip s3://blackjack-game-site/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Apply Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve
